project_id = "opkvvdgnhhopkkeaokzo"

[functions.create-user]
verify_jwt = false

[functions.process-royalty-upload]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.update-user-status]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.remove-artist-from-label]
verify_jwt = false

[functions.change-own-password]
verify_jwt = false

[functions.gcs-upload]
verify_jwt = false

[functions.update-app-settings]
verify_jwt = false

[functions.get-ga4-config]
verify_jwt = false

[functions.send-royalty-notification]
verify_jwt = false
