# quick-fix-supabase.sh
# Script sederhana untuk memperbaiki Supabase

echo "=== Quick Fix Supabase Self-Hosted ==="
echo ""
echo "Langkah-langkah yang perlu dilakukan di server Supabase:"
echo ""
echo "1. Masuk ke direktori Supabase:"
echo "   cd ~/docker/supabase/supabase/docker"
echo ""
echo "2. Cek apakah file .env ada:"
echo "   ls -la .env"
echo ""
echo "3. Jika tidak ada, copy dari template:"
echo "   cp .env.example .env"
echo ""
echo "   Atau download dari GitHub:"
echo "   curl -o .env https://raw.githubusercontent.com/supabase/supabase/master/docker/.env.example"
echo ""
echo "4. Generate secrets menggunakan openssl:"
echo "   echo \"JWT_SECRET=\\""
echo "   echo \"POSTGRES_PASSWORD=\\""
echo "   echo \"VAULT_ENC_KEY=\\""
echo "   echo \"PG_META_CRYPTO_KEY=\\""
echo "   echo \"SECRET_KEY_BASE=\\""
echo ""
echo "5. Edit file .env dan isi minimal variabel berikut:"
echo "   nano .env"
echo ""
echo "   POSTGRES_PASSWORD=<hasil generate>"
echo "   JWT_SECRET=<hasil generate>"
echo "   ANON_KEY=<generate di jwt.io atau supabase cli>"
echo "   SERVICE_ROLE_KEY=<generate di jwt.io atau supabase cli>"
echo "   DASHBOARD_USERNAME=admin"
echo "   DASHBOARD_PASSWORD=<password aman>"
echo "   SITE_URL=https://web.maskhar.com"
echo "   API_EXTERNAL_URL=https://supabase.carubra.com"
echo "   SUPABASE_PUBLIC_URL=https://supabase.carubra.com"
echo "   POSTGRES_HOST=db"
echo "   POSTGRES_DB=postgres"
echo "   POSTGRES_PORT=5432"
echo "   PGRST_DB_SCHEMAS=public,storage,graphql_public"
echo "   KONG_HTTP_PORT=8000"
echo "   KONG_HTTPS_PORT=8443"
echo ""
echo "   # Google OAuth"
echo "   GOTRUE_EXTERNAL_GOOGLE_ENABLED=true"
echo "   GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=<dari Google Cloud Console>"
echo "   GOTRUE_EXTERNAL_GOOGLE_SECRET=<dari Google Cloud Console>"
echo "   GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=https://supabase.carubra.com/auth/v1/callback"
echo ""
echo "6. Restart Supabase:"
echo "   docker compose down"
echo "   docker compose up -d"
echo ""
echo "7. Cek status:"
echo "   docker compose ps"
echo ""
echo "8. Cek logs jika ada error:"
echo "   docker compose logs -f"
echo ""
echo "=== Generate JWT Keys ==="
echo ""
echo "Untuk generate ANON_KEY dan SERVICE_ROLE_KEY:"
echo ""
echo "Option 1: Menggunakan jwt.io"
echo "1. Buka https://jwt.io"
echo "2. Pilih algorithm: HS256"
echo "3. Masukkan secret: <JWT_SECRET dari step 4>"
echo "4. Payload untuk ANON_KEY:"
echo "   {"
echo "     \"iss\": \"supabase\","
echo "     \"role\": \"anon\","
echo "     \"exp\": 1983812996"
echo "   }"
echo "5. Payload untuk SERVICE_ROLE_KEY:"
echo "   {"
echo "     \"iss\": \"supabase\","
echo "     \"role\": \"service_role\","
echo "     \"exp\": 1983812996"
echo "   }"
echo ""
echo "Option 2: Menggunakan Supabase CLI (jika sudah install)"
echo "   npx supabase gen keys --anon"
echo "   npx supabase gen keys --service-role"
echo ""
echo "=== Verifikasi Google OAuth ==="
echo ""
echo "1. Di Google Cloud Console (console.cloud.google.com):"
echo "   - APIs & Services > Credentials"
echo "   - Pilih OAuth 2.0 Client ID"
echo "   - Authorized redirect URIs harus ada:"
echo "     https://supabase.carubra.com/auth/v1/callback"
echo ""
echo "2. Di Supabase Dashboard (https://supabase.carubra.com):"
echo "   - Login dengan DASHBOARD_USERNAME dan DASHBOARD_PASSWORD"
echo "   - Authentication > Providers > Google"
echo "   - Enable dan masukkan Client ID & Secret"
echo "   - Save"
echo ""
echo "3. Test di aplikasi (https://web.maskhar.com):"
echo "   - Klik 'Login dengan Google'"
echo "   - Seharusnya redirect ke Google OAuth"
echo "   - Setelah authorize, redirect kembali ke aplikasi"
echo ""
